version: "3"

services:
  mongodb:
    container_name: "backuper-mongodb"
    image: "mongo:4.2"
    ports:
      - "27217:27017"
    restart: always

  api:
    container_name: "backuper-api"
    image: node:10
    volumes:
      - ../:/home/node/app
    working_dir: /home/node/app
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    expose:
      - "4000"
    ports:
      - 4000:8100
    command: bash -c 'npm install && npm run start'
